### ISSUE TITLE
Error in the logs

### ISSUE THREAD

**Issue by CH-Tefi** [bhuebschen/dreame-mower#2]
I recieve the following errors in the log.

`
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dreame_mower.dreame.protocol
Quelle: custom_components/dreame_mower/dreame/protocol.py:209
Integration: Dreame Mower (Dokumentation, Probleme)
Erstmals aufgetreten: 26. Juli 2024 um 18:26:17 (587 Vorkommnisse)
Zuletzt protokolliert: 06:24:08

Message received: {"id":895,"did":-110186894,"data":{"params":[{"siid":1,"piid":1,"value":[1,0,0,0,0,0,0,0,0,0,228,14,0,0,0,1,156,175,128,206,189,0,0,0],"did":-110186894}],"method":"properties_changed","id":895}}
Message received: {"id":898,"did":-110186894,"data":{"params":[{"siid":1,"piid":1,"value":[1,0,0,0,0,0,0,0,0,0,228,14,0,0,0,1,156,176,128,206,190,0,0,0],"did":-110186894}],"method":"properties_changed","id":898}}
Message received: {"id":901,"did":-110186894,"data":{"params":[{"siid":1,"piid":1,"value":[1,0,0,0,0,0,0,0,0,0,228,14,0,0,0,1,156,175,128,206,191,0,0,0],"did":-110186894}],"method":"properties_changed","id":901}}
Message received: {"id":903,"did":-110186894,"data":{"params":[{"siid":1,"piid":1,"value":[1,0,0,0,0,0,0,0,0,0,228,14,0,0,0,1,156,176,128,206,192,0,0,0],"did":-110186894}],"method":"properties_changed","id":903}}
Message received: {"id":905,"did":-110186894,"data":{"params":[{"siid":1,"piid":1,"value":[1,0,0,0,0,0,0,0,0,0,228,14,0,0,0,1,156,175,128,206,193,0,0,0],"did":-110186894}],"method":"properties_changed","id":905}}
`

**Comment by CH-Tefi** [comment]
and also:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/dreame_mower/dreame/device.py:4994
Integration: Dreame Mower (Dokumentation, Probleme)
Erstmals aufgetreten: 06:42:40 (3 Vorkommnisse)
Zuletzt protokolliert: 06:42:43

Error doing job: Exception in callback DreameMowerDataUpdateCoordinator.async_set_updated_data(None) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/dreame_mower/coordinator.py", line 381, in async_set_updated_data
    super().async_set_updated_data(self._device)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 447, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/config/custom_components/dreame_mower/entity.py", line 151, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    available = self.available  # only call self.available once per update cycle
                ^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_mower/entity.py", line 190, in available
    return self.entity_description.available_fn(self.device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_mower/dreame/types.py", line 1017, in <lambda>
    DreameMowerAction.RESET_LENSBRUSH.name: lambda device: bool(device.status.lensbrush_life < 100),
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_mower/dreame/device.py", line 4994, in lensbrush_life
    return 30000 - self._get_property(DreameMowerProperty.LENSBRUSH_LEFT)['CMS'][0]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'CMS'

**Comment by antondaubert** [comment]
The first issue about the "error" in `Message received` is fixed in #21. I mean, it wasn't really an error, just the wrong log level was wrong.

The one from the second post I haven't see yet. Is still up to date?

**Comment by bhuebschen** [comment]
the lensbrush error exists since the first version - everything takes a lot of time to implement.. and time is unfortunately the thing I have the least of

**Comment by antondaubert** [comment]
Is this related or the same as bug #23 ?

**Comment by bhuebschen** [comment]
> Is this related or the same as bug [#23](https://github.com/bhuebschen/dreame-mower/issues/23) ?

No.. that's another matter altogether.. LENSBRUSH_LEFT has to do with the consumables.. while #23 is a mapping to wrong error-codes (vacuum <-> mower)

**Comment by antondaubert** [comment]
Got it.

Made it fail gracefully as part of #24, see https://github.com/bhuebschen/dreame-mower/pull/24/commits/44a01e99b9c53e51a8c39ad560ec62a157609e99. ptal
